name: Benchmark a pull request

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@v0.6
        with:
          julia-version: "1"
          force-time-unit: "ns"
